[build]
builder = "NIXPACKS"
nixpacksConfigPath = "railway.build.toml"

[deploy]
runtime = "V2"
numReplicas = 1
# region = "us-west1"
# healthcheckPath = "/health"
# healthcheckTimeout = 90
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
